fix win32 warnings after platform update
- mmsysio - prevent redefinition of S_IFLNK macro

- file-api-tests : fix compilation warning
  error: absolute value function 'abs' given an argument of type 'long long int'
         but has parameter of type 'int' which may cause truncation of value

Change-Id: I7f1d075c35cc0aea9b7eff09b4a3653c60588e13