error: remove deprecated error codes
Remove the deprecated error codes:
	MM_EUNKNOWNUSER
	MM_EWRONGPWD
	MM_ETOOMANY
	MM_ENOCALIB
	MM_ENOINERTIAL
	MM_ECAMERROR

Those error codes should have been removed before the last release.
Since it was recent, we do it now.

Change-Id: I81c7d3b2b15226c7e2049b257303e172a6783514